#
# This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

codecov:
  branch: main
  require_ci_to_pass: true
ignore:
  - "**/*.stories.tsx"
comment:
  behavior: default
  layout: reach,diff,flags,files,footer
  require_changes: false
coverage:
  precision: 2
  range:
    - 70.0
    - 90.0
  round: up
  status:
    patch:
      default:
        target: auto
        threshold: 5.0
    project:
      default:
        target: auto
        threshold: 5.0
parsers:
  v1:
    include_full_missed_files: true
