//
// This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
//
// SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as DashboardImport } from './routes/~_dashboard'
import { Route as SignInIndexImport } from './routes/~sign-in/~index'
import { Route as DashboardIndexImport } from './routes/~_dashboard/~index'
import { Route as DashboardUsersInviteImport } from './routes/~_dashboard/~users/~invite'
import { Route as DashboardUsersIdImport } from './routes/~_dashboard/~users/~$id'
import { Route as DashboardPatientsInviteImport } from './routes/~_dashboard/~patients/~invite'
import { Route as DashboardUsersIndexImport } from './routes/~_dashboard/~users/~index'
import { Route as DashboardPatientsIndexImport } from './routes/~_dashboard/~patients/~index'
import { Route as DashboardPatientsIdIndexImport } from './routes/~_dashboard/~patients/~$id/~index'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const SignInIndexRoute = SignInIndexImport.update({
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersInviteRoute = DashboardUsersInviteImport.update({
  path: '/users/invite',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersIdRoute = DashboardUsersIdImport.update({
  path: '/users/$id',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPatientsInviteRoute = DashboardPatientsInviteImport.update({
  path: '/patients/invite',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersIndexRoute = DashboardUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPatientsIndexRoute = DashboardPatientsIndexImport.update({
  path: '/patients/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPatientsIdIndexRoute = DashboardPatientsIdIndexImport.update({
  path: '/patients/$id/',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/patients/': {
      id: '/_dashboard/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashboardPatientsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/patients/invite': {
      id: '/_dashboard/patients/invite'
      path: '/patients/invite'
      fullPath: '/patients/invite'
      preLoaderRoute: typeof DashboardPatientsInviteImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users/$id': {
      id: '/_dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof DashboardUsersIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users/invite': {
      id: '/_dashboard/users/invite'
      path: '/users/invite'
      fullPath: '/users/invite'
      preLoaderRoute: typeof DashboardUsersInviteImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/patients/$id/': {
      id: '/_dashboard/patients/$id/'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof DashboardPatientsIdIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DashboardRoute: DashboardRoute.addChildren({
    DashboardIndexRoute,
    DashboardPatientsIndexRoute,
    DashboardUsersIndexRoute,
    DashboardPatientsInviteRoute,
    DashboardUsersIdRoute,
    DashboardUsersInviteRoute,
    DashboardPatientsIdIndexRoute,
  }),
  SignInIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/_dashboard",
        "/sign-in/"
      ]
    },
    "/_dashboard": {
      "filePath": "~_dashboard.tsx",
      "children": [
        "/_dashboard/",
        "/_dashboard/patients/",
        "/_dashboard/users/",
        "/_dashboard/patients/invite",
        "/_dashboard/users/$id",
        "/_dashboard/users/invite",
        "/_dashboard/patients/$id/"
      ]
    },
    "/_dashboard/": {
      "filePath": "~_dashboard/~index.tsx",
      "parent": "/_dashboard"
    },
    "/sign-in/": {
      "filePath": "~sign-in/~index.tsx"
    },
    "/_dashboard/patients/": {
      "filePath": "~_dashboard/~patients/~index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/users/": {
      "filePath": "~_dashboard/~users/~index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/patients/invite": {
      "filePath": "~_dashboard/~patients/~invite.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/users/$id": {
      "filePath": "~_dashboard/~users/~$id.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/users/invite": {
      "filePath": "~_dashboard/~users/~invite.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/patients/$id/": {
      "filePath": "~_dashboard/~patients/~$id/~index.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
