//
// This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
//
// SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
/* eslint-disable */
type ImportMetaEnv = {
  // Auto-generated by `npx vite-envs update-types` and hot-reloaded by the `vite-env` plugin
  // You probably want to add `/src/vite-env.d.ts` to your .prettierignore
  VITE_PUBLIC_FIREBASE_API_KEY: string
  VITE_PUBLIC_FIREBASE_APP_ID: string
  VITE_PUBLIC_FIREBASE_AUTH_DOMAIN: string
  VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string
  VITE_PUBLIC_FIREBASE_PROJECT_ID: string
  VITE_PUBLIC_FIREBASE_STORAGE_BUCKET: string
  VITE_PUBLIC_EMULATOR: string
  VITE_PUBLIC_EMAIL_PASSWORD_SIGN_IN: string
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  // @user-defined-start
  /*
   *  You can use this section to explicitly extend the type definition of `import.meta.env`
   *  This is useful if you're using Vite plugins that define specific `import.meta.env` properties.
   *  If you're not using such plugins, this section should remain as is.
   */
  SSR: boolean
  // @user-defined-end
}

interface ImportMeta {
  // Auto-generated by `npx vite-envs update-types`

  url: string

  readonly hot?: import('vite-envs/types/hot').ViteHotContext

  readonly env: ImportMetaEnv

  glob: import('vite-envs/types/importGlob').ImportGlobFunction
}
